export const CARS = [
  {
    id: 1,
    name: 'Toyota Camry',
    category: 'Compact',
    fuel: 'Hybrid',
    year: 2024,
    seats: 5,
    transmission: 'Automatic',
    price: 89,
    weeklyPrice: 560,
    rating: 4.5,
    trips: 128,
    available: true,
    badge: 'Compact',
    fuelBadge: 'Hybrid',
    fuelColor: '#16a34a',
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&q=80',
    features: ['Bluetooth', 'Backup Camera', 'Apple CarPlay'],
    specs: { engine: '2.5L Hybrid', power: '218 HP', torque: '221 Nm', acceleration: '7.8s', topSpeed: '200 km/h', fuel: '4.2L/100km' },
    description: 'The perfect blend of comfort and efficiency. The Toyota Camry Hybrid delivers exceptional fuel economy without sacrificing the premium comfort you deserve.',
    location: 'Melbourne Airport (MEL)',
    allFeatures: ['Bluetooth', 'Backup Camera', 'Apple CarPlay', 'Heated Seats', 'Cruise Control', 'Lane Assist', 'Wireless Charging', 'Sunroof'],
    included: ['Insurance Included', 'Unlimited KM in VIC', 'Free Cancellation', '24/7 Roadside Assist'],
    deposit: 300, minAge: 21, minDays: 1,
    host: { name: 'Jenny K.', avatar: 'JK', rating: 4.95, trips: 2100, responseTime: '< 15 min', joined: '2019' },
    reviews: [
      { name: 'Mark B.', rating: 5, date: 'Feb 2026', text: 'Great value, clean car, easy process. Perfect for getting around Melbourne.' },
      { name: 'Sophie N.', rating: 5, date: 'Jan 2026', text: 'Jenny was the best host! Car was spotless. Will 100% book again.' },
    ],
  },
  {
    id: 2,
    name: 'Tesla Model 3',
    category: 'Luxury',
    fuel: 'Electric',
    year: 2024,
    seats: 5,
    transmission: 'Automatic',
    price: 149,
    weeklyPrice: 950,
    rating: 4.9,
    trips: 214,
    available: true,
    badge: 'Luxury',
    fuelBadge: 'Electric',
    fuelColor: '#2563eb',
    image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=600&q=80',
    features: ['Autopilot', '15" Touchscreen', 'Free Charging'],
    specs: { engine: 'Dual Motor Electric', power: '346 HP', torque: '493 Nm', acceleration: '4.4s', topSpeed: '225 km/h', fuel: '14.9kWh/100km' },
    description: 'Experience the future of driving. The Tesla Model 3 combines cutting-edge technology with exhilarating performance and up to 500km of range.',
    location: 'Melbourne CBD',
    allFeatures: ['Autopilot', '15" Touchscreen', 'Free Supercharging', 'Glass Roof', 'Over-the-Air Updates', 'Sentry Mode', 'Dog Mode', 'Premium Audio'],
    included: ['Insurance Included', 'Free Supercharging', 'Unlimited KM in VIC', 'Free Cancellation'],
    deposit: 500, minAge: 21, minDays: 1,
    host: { name: 'Priya S.', avatar: 'PS', rating: 4.98, trips: 890, responseTime: '< 30 min', joined: '2022' },
    reviews: [
      { name: 'Tom W.', rating: 5, date: 'Feb 2026', text: 'The Tesla was absolutely incredible. Autopilot on the freeway is a game changer!' },
      { name: 'Emma L.', rating: 5, date: 'Jan 2026', text: 'So smooth and quiet. Free charging saved us a lot. The host was amazing too.' },
    ],
  },
  {
    id: 3,
    name: 'BMW X5 xDrive40i',
    category: 'SUV',
    fuel: 'Petrol',
    year: 2024,
    seats: 7,
    transmission: 'Automatic',
    price: 199,
    weeklyPrice: 1250,
    rating: 4.7,
    trips: 89,
    available: true,
    badge: 'SUV',
    fuelBadge: 'Petrol',
    fuelColor: '#6b7280',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80',
    features: ['Panoramic Sunroof', 'Harman Kardon', 'Heads-Up Display'],
    specs: { engine: '3.0L TwinPower Turbo', power: '340 HP', torque: '450 Nm', acceleration: '5.5s', topSpeed: '250 km/h', fuel: '9.8L/100km' },
    description: 'The ultimate luxury SUV experience. The BMW X5 combines breathtaking performance with 7-seat versatility and the finest premium materials.',
    location: 'Tullamarine',
    allFeatures: ['Panoramic Sunroof', 'Harman Kardon Sound', 'Heads-Up Display', '7 Seats', 'Air Suspension', 'Gesture Control', 'Wireless Charging', '4WD'],
    included: ['Insurance Included', 'Unlimited KM in VIC', '24/7 Roadside Assist', 'Free Cancellation'],
    deposit: 800, minAge: 25, minDays: 2,
    host: { name: 'Michael T.', avatar: 'MT', rating: 5.0, trips: 312, responseTime: '< 1 hour', joined: '2021' },
    reviews: [
      { name: 'Sarah K.', rating: 5, date: 'Feb 2026', text: 'Immaculate car, exactly as described. Michael was super responsive.' },
      { name: 'James R.', rating: 5, date: 'Jan 2026', text: 'Best car rental experience ever. The BMW was spotless and drove like a dream.' },
    ],
  },
  {
    id: 4,
    name: 'Hyundai i30',
    category: 'Economy',
    fuel: 'Petrol',
    year: 2023,
    seats: 5,
    transmission: 'Manual',
    price: 59,
    weeklyPrice: 380,
    rating: 4.3,
    trips: 67,
    available: true,
    badge: 'Economy',
    fuelBadge: 'Petrol',
    fuelColor: '#6b7280',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&q=80',
    features: ['Lane Keep Assist', 'Wireless Charging', 'Rear Sensors'],
    specs: { engine: '1.6L GDI', power: '132 HP', torque: '165 Nm', acceleration: '10.2s', topSpeed: '185 km/h', fuel: '7.0L/100km' },
    description: 'Smart, efficient and easy to drive. The Hyundai i30 is perfect for navigating Melbourne\'s streets without breaking the bank.',
    location: 'Richmond',
    allFeatures: ['Lane Keep Assist', 'Wireless Charging', 'Rear Sensors', 'Apple CarPlay', 'Reverse Camera', 'Blind Spot Warning', 'Cruise Control', 'LED Headlights'],
    included: ['Insurance Included', 'Unlimited KM in VIC', 'Free Cancellation'],
    deposit: 200, minAge: 18, minDays: 1,
    host: { name: 'David C.', avatar: 'DC', rating: 4.9, trips: 456, responseTime: '< 2 hours', joined: '2020' },
    reviews: [
      { name: 'Anika R.', rating: 4, date: 'Feb 2026', text: 'Good value car, easy process. Great for getting around the city.' },
      { name: 'Steve M.', rating: 5, date: 'Dec 2025', text: 'Simple, clean and affordable. Exactly what I needed.' },
    ],
  },
  {
    id: 5,
    name: 'Mercedes-Benz GLE 450',
    category: 'Luxury',
    fuel: 'Hybrid',
    year: 2024,
    seats: 5,
    transmission: 'Automatic',
    price: 259,
    weeklyPrice: 1650,
    rating: 4.8,
    trips: 43,
    available: false,
    badge: 'Luxury',
    fuelBadge: 'Hybrid',
    fuelColor: '#16a34a',
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=600&q=80',
    features: ['Burmester Sound', 'MBUX AI', 'Air Suspension'],
    specs: { engine: '3.0L EQ Boost Hybrid', power: '367 HP', torque: '500 Nm', acceleration: '5.7s', topSpeed: '250 km/h', fuel: '8.3L/100km' },
    description: 'The pinnacle of luxury SUV engineering. The GLE 450 Hybrid combines Mercedes-Benz\'s finest craftsmanship with cutting-edge electrification technology.',
    location: 'Southbank',
    allFeatures: ['Burmester Sound', 'MBUX AI Assistant', 'Air Suspension', 'Massage Seats', 'Ambient Lighting', 'Night Vision', 'Augmented Reality Nav', 'Wireless Charging'],
    included: ['Insurance Included', 'Unlimited KM in VIC', '24/7 Roadside Assist', 'Free Cancellation'],
    deposit: 1000, minAge: 25, minDays: 2,
    host: { name: 'Alex P.', avatar: 'AP', rating: 4.96, trips: 145, responseTime: '< 1 hour', joined: '2022' },
    reviews: [
      { name: 'Raj M.', rating: 5, date: 'Jan 2026', text: 'Used it for a business meeting. Arrived in absolute style.' },
      { name: 'Lisa T.', rating: 5, date: 'Nov 2025', text: 'Beautiful car, very comfortable. Alex was great.' },
    ],
  },
  {
    id: 6,
    name: 'Ford Ranger XLT',
    category: 'Van',
    fuel: 'Diesel',
    year: 2023,
    seats: 5,
    transmission: 'Automatic',
    price: 129,
    weeklyPrice: 820,
    rating: 4.6,
    trips: 102,
    available: true,
    badge: 'VAN',
    fuelBadge: 'Diesel',
    fuelColor: '#6b7280',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    features: ['4WD', 'Tow Package', 'Sync 4 Infotainment'],
    specs: { engine: '2.0L Bi-Turbo Diesel', power: '213 HP', torque: '500 Nm', acceleration: '9.5s', topSpeed: '175 km/h', fuel: '8.5L/100km' },
    description: 'Built for work and adventure. The Ford Ranger XLT handles everything from city deliveries to remote outback tracks with ease.',
    location: 'Dandenong',
    allFeatures: ['4WD with Locking Diff', 'Tow Bar (3.5T)', 'Sync 4 Infotainment', 'Reverse Camera', 'Ford Co-Pilot 360', 'Off-Road Modes', 'Trail Control', 'LED Work Lights'],
    included: ['Insurance Included', 'Unlimited KM in VIC', '24/7 Roadside Assist', 'Free Cancellation'],
    deposit: 600, minAge: 21, minDays: 1,
    host: { name: 'Brett O.', avatar: 'BO', rating: 4.99, trips: 203, responseTime: '< 1 hour', joined: '2021' },
    reviews: [
      { name: 'Chris V.', rating: 5, date: 'Feb 2026', text: 'Took it to Wilsons Promontory. Absolute beast off-road. Brett was super helpful.' },
      { name: 'Dylan F.', rating: 5, date: 'Dec 2025', text: 'Perfect for our camping trip. Loved it.' },
    ],
  },
  {
    id: 7,
    name: 'Kia EV6 GT-Line',
    category: 'Compact',
    fuel: 'Electric',
    year: 2024,
    seats: 5,
    transmission: 'Automatic',
    price: 109,
    weeklyPrice: 700,
    rating: 4.7,
    trips: 78,
    available: true,
    badge: 'Compact',
    fuelBadge: 'Electric',
    fuelColor: '#2563eb',
    image: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=600&q=80',
    features: ['800V Fast Charge', 'Head-Up Display', 'Meridian Sound'],
    specs: { engine: 'Dual Motor Electric', power: '320 HP', torque: '605 Nm', acceleration: '5.1s', topSpeed: '185 km/h', fuel: '18.0kWh/100km' },
    description: 'The most exciting electric crossover on the market. The Kia EV6 GT-Line delivers supercar-beating acceleration with everyday practicality.',
    location: 'St Kilda',
    allFeatures: ['800V Ultra-Fast Charging', 'Augmented Reality HUD', 'Meridian Sound', 'Matrix LED Lights', 'Remote Parking', 'Vehicle-to-Load', 'Bose Audio', 'Panoramic Roof'],
    included: ['Insurance Included', 'Unlimited KM in VIC', 'Free Cancellation', '24/7 Roadside Assist'],
    deposit: 400, minAge: 21, minDays: 1,
    host: { name: 'Jenny K.', avatar: 'JK', rating: 4.95, trips: 2100, responseTime: '< 15 min', joined: '2019' },
    reviews: [
      { name: 'Tom H.', rating: 5, date: 'Feb 2026', text: 'The EV6 blew my mind. Fastest car I\'ve ever been in. Charges in 20 mins!' },
      { name: 'Mia S.', rating: 5, date: 'Jan 2026', text: 'So fun to drive. Love the head-up display. Will definitely rent again.' },
    ],
  },
  {
    id: 8,
    name: 'Toyota RAV4 Hybrid',
    category: 'SUV',
    fuel: 'Hybrid',
    year: 2024,
    seats: 5,
    transmission: 'Automatic',
    price: 139,
    weeklyPrice: 890,
    rating: 4.6,
    trips: 155,
    available: true,
    badge: 'SUV',
    fuelBadge: 'Hybrid',
    fuelColor: '#16a34a',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600&q=80',
    features: ['AWD', 'Safety Sense', 'Apple CarPlay'],
    specs: { engine: '2.5L Hybrid AWD', power: '222 HP', torque: '163 Nm', acceleration: '8.1s', topSpeed: '180 km/h', fuel: '4.7L/100km' },
    description: 'Australia\'s most popular SUV — and for good reason. The RAV4 Hybrid AWD combines incredible fuel efficiency with genuine all-weather capability.',
    location: 'Frankston',
    allFeatures: ['All-Wheel Drive', 'Toyota Safety Sense 3.0', 'Apple CarPlay & Android Auto', 'Wireless Charging', 'JBL Audio', 'Panoramic View Monitor', 'Power Tailgate', 'Ventilated Seats'],
    included: ['Insurance Included', 'Unlimited KM in VIC', 'Free Cancellation', '24/7 Roadside Assist'],
    deposit: 400, minAge: 21, minDays: 1,
    host: { name: 'Sarah M.', avatar: 'SM', rating: 4.97, trips: 678, responseTime: '< 30 min', joined: '2020' },
    reviews: [
      { name: 'Ben L.', rating: 5, date: 'Feb 2026', text: 'Perfect family car. Fuel economy was amazing. Sarah was very responsive.' },
      { name: 'Grace T.', rating: 4, date: 'Jan 2026', text: 'Comfortable and reliable. Great for our weekend trip to the Dandenong Ranges.' },
    ],
  },
];

export type Car = typeof CARS[0];
